### ISSUE TITLE
Not OK 400 'Secondary device not authorized!'

### ISSUE THREAD

**Issue by baiandin** [ShonP40/ha-palgate#10]
## Version of the custom_component
1.2.3

## Configuration
Done as described.

## Describe the bug
Control the gates (Linked Device Number = 1) doesn't work and return error:
Failed to perform the action cover/open_cover. Not OK 400 {'err': 'not authorized', 'msg': 'Secondary device not authorized!', 'status': 'failed'}
If Linked Device Number = 0 or 2, it return error 401.

## Debug log
```text

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:17:47 PM (1 occurrences)
Last logged: 6:17:47 PM

[139668939832576] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/palgate/cover.py", line 94, in async_open_cover
    await self.api.open_gate()
  File "/config/custom_components/palgate/api.py", line 85, in open_gate
    raise Error(f"Not OK {resp.status} {error_text}")
voluptuous.error.Error: Not OK 400 {'err': 'not authorized', 'msg': 'Secondary device not authorized!', 'status': 'failed'}

```

**Comment by ShonP40** [comment]
Try to unlink Home Assistant from PalGate, remove your PalGate setup from HA
Then restart HA and try to set it up again.

**Comment by baiandin** [comment]
Didn't help.
Maybe regional specificity (Russia)?

**Comment by doron1** [comment]
> Didn't help.

The message ("Secondary device not authorized!") seems to indicate that the secondary device is not authorized to act on the specific gate (device ID). Does your Palgate app operate your gate properly?

**Comment by baiandin** [comment]
Yes, I can open gates via the Palgate app and also via Google Home integration.

**Comment by doron1** [comment]
1. Are you _sure_ you configured the correct **device ID** for the specific gate? 
2. Assuming the answer to the above is yes, can you try to add another mobile phone as a second linked device, and try to open the gate with that secondary mobile phone app?

**Comment by baiandin** [comment]
1. Sure.
2. I added another mobile phone as a second linked device and in this case the gate doesn't open in the Palgate app, the message "Realy disabled, please contact Admin" is shown.
That's the reason, in my case (apartment building with HOA) it will not work.
Thank you.

**Comment by ShonP40** [comment]
Can you open the gate with your main device then?

Or is it completely disabled

**Comment by baiandin** [comment]
Yes, I can.
Restriction on secondary devices only.

**Comment by ShonP40** [comment]
Guessing that the only thing you can do is contact whoever installed your gate and ask them to allow secondary devices.

**Comment by doron1** [comment]
It might be that your mobile app is already designated as a "Secondary Device" of some sorts (this might be the way they are managing apartment buildings' gates), so it does not allow further relaying. Just a guess though.

One question though @baiandin : When you ran the token generation tool (scan QR code etc.) - did it report successful completion? Provided a token etc., with no indication of an issue?

**Comment by baiandin** [comment]
I think so too.
Token generator successfully linked, showed the token, token type 1, correct phone number. There were no issues.

**Comment by ostratonov** [comment]
@baiandin same happened for me today. have you managed to resolve your issue? any tips?

**Comment by baiandin** [comment]
@ostratonov I did it differently.
PalGate integrates into Google Home. HA sends a voice command to open the gate via Google Assistant SDK integration.
Guides:
https://youtu.be/1P35ANoelys?si=35mtT2zEnZDPKU1g
https://youtu.be/I3wkvYzjeiA?si=ACpHOmTOMoeKiLef

Script for opening the gates:
open Gate A
```
sequence:
  - action: google_assistant_sdk.send_text_command
    data:
      command: open Gate A
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: input_boolean.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.gate_a_state
  - delay:
      hours: 0
      minutes: 0
      seconds: 35
      milliseconds: 0
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.gate_a_state
alias: open Gate A
description: ""
```
close Gate A
```
sequence:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.gate_a_state
alias: close Gate A
description: ""
```

Helper object configuration.yaml:
```
input_boolean:
  gate_a_state:
    name: "Gate A state"
    initial: off
cover:
  - platform: template
    covers:
      gate_a:
        device_class: garage
        icon_template: mdi:boom-gate-arrow-up-outline
        friendly_name: "Gate A"
        value_template: >-
          {% if is_state('input_boolean.gate_a_state', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        open_cover:
          action: script.open_gate_a
        close_cover:
          action: script.close_gate_a
```
